// @ts-nocheck
import type { TechConfig } from '../shared/economy.js';

export const LOCAL_TECH_CONFIGS: TechConfig[] = [
  {
    id: crypto.randomUUID(),
    techId: 'COLLECTION_EFFICIENT_I',
    name: 'Efficient Collection I',
    description: 'Increases all resource production by 5%',
    category: 'ECONOMY',
    maxLevel: 1,
    costGold: 200,
    costWood: 100,
    costStone: 50,
    costFood: 50,
    researchTimeSeconds: 300,
    prerequisites: [],
    mutuallyExclusive: [],
    effects: [{ type: 'RESOURCE_PROD', target: 'all', stat: 'production', value: 0.05, operation: 'ADD' }],
  },
  {
    id: crypto.randomUUID(),
    techId: 'COLLECTION_EFFICIENT_II',
    name: 'Efficient Collection II',
    description: 'Increases all resource production by 10%',
    category: 'ECONOMY',
    maxLevel: 1,
    costGold: 500,
    costWood: 300,
    costStone: 150,
    costFood: 150,
    researchTimeSeconds: 600,
    prerequisites: ['COLLECTION_EFFICIENT_I'],
    mutuallyExclusive: [],
    effects: [{ type: 'RESOURCE_PROD', target: 'all', stat: 'production', value: 0.10, operation: 'ADD' }],
  },
  {
    id: crypto.randomUUID(),
    techId: 'COLLECTION_EFFICIENT_III',
    name: 'Efficient Collection III',
    description: 'Increases all resource production by 15%',
    category: 'ECONOMY',
    maxLevel: 1,
    costGold: 1200,
    costWood: 800,
    costStone: 400,
    costFood: 400,
    researchTimeSeconds: 1200,
    prerequisites: ['COLLECTION_EFFICIENT_II'],
    mutuallyExclusive: [],
    effects: [{ type: 'RESOURCE_PROD', target: 'all', stat: 'production', value: 0.15, operation: 'ADD' }],
  },
  {
    id: crypto.randomUUID(),
    techId: 'ADVANCED_STORAGE',
    name: 'Advanced Storage',
    description: 'Increases storage capacity by 20%',
    category: 'ECONOMY',
    maxLevel: 1,
    costGold: 400,
    costWood: 300,
    costStone: 200,
    costFood: 100,
    researchTimeSeconds: 480,
    prerequisites: ['COLLECTION_EFFICIENT_I'],
    mutuallyExclusive: [],
    effects: [{ type: 'BUILDING_STAT', target: 'STORAGE', stat: 'capacity', value: 1.2, operation: 'MULTIPLY' }],
  },
  {
    id: crypto.randomUUID(),
    techId: 'WARTIME_ECONOMY',
    name: 'Wartime Economy',
    description: 'Reduces unit training costs by 15%',
    category: 'ECONOMY',
    maxLevel: 1,
    costGold: 800,
    costWood: 600,
    costStone: 300,
    costFood: 300,
    researchTimeSeconds: 900,
    prerequisites: ['COLLECTION_EFFICIENT_II'],
    mutuallyExclusive: [],
    effects: [{ type: 'GLOBAL_BONUS', target: 'trainingCostReduction', stat: 'cost', value: 0.15, operation: 'ADD' }],
  },
  {
    id: crypto.randomUUID(),
    techId: 'TRADE',
    name: 'Trade Routes',
    description: 'Unlocks market trading and increases gold production by 10%',
    category: 'ECONOMY',
    maxLevel: 1,
    costGold: 600,
    costWood: 400,
    costStone: 200,
    costFood: 200,
    researchTimeSeconds: 720,
    prerequisites: ['COLLECTION_EFFICIENT_I'],
    mutuallyExclusive: [],
    effects: [{ type: 'RESOURCE_PROD', target: 'gold', stat: 'production', value: 0.10, operation: 'ADD' }],
  },
  {
    id: crypto.randomUUID(),
    techId: 'WEAPON_FORGE_I',
    name: 'Weapon Forge I',
    description: 'Increases all unit attack by 10%',
    category: 'MILITARY',
    maxLevel: 1,
    costGold: 300,
    costWood: 200,
    costStone: 100,
    costFood: 50,
    researchTimeSeconds: 360,
    prerequisites: [],
    mutuallyExclusive: [],
    effects: [{ type: 'UNIT_STAT', target: 'all', stat: 'attack', value: 0.10, operation: 'ADD' }],
  },
  {
    id: crypto.randomUUID(),
    techId: 'WEAPON_FORGE_II',
    name: 'Weapon Forge II',
    description: 'Increases all unit attack by 15% and armor penetration by 5',
    category: 'MILITARY',
    maxLevel: 1,
    costGold: 700,
    costWood: 500,
    costStone: 300,
    costFood: 150,
    researchTimeSeconds: 720,
    prerequisites: ['WEAPON_FORGE_I'],
    mutuallyExclusive: [],
    effects: [
      { type: 'UNIT_STAT', target: 'all', stat: 'attack', value: 0.15, operation: 'ADD' },
      { type: 'UNIT_STAT', target: 'all', stat: 'armorPenetration', value: 5, operation: 'ADD' },
    ],
  },
  {
    id: crypto.randomUUID(),
    techId: 'REINFORCED_BOWS',
    name: 'Reinforced Bows',
    description: 'Archer attack +20% and range bonus',
    category: 'MILITARY',
    maxLevel: 1,
    costGold: 500,
    costWood: 400,
    costStone: 100,
    costFood: 100,
    researchTimeSeconds: 540,
    prerequisites: ['WEAPON_FORGE_I'],
    mutuallyExclusive: [],
    effects: [{ type: 'UNIT_STAT', target: 'ARCHER', stat: 'attack', value: 0.20, operation: 'ADD' }],
  },
  {
    id: crypto.randomUUID(),
    techId: 'HORSE_BREEDING',
    name: 'Horse Breeding',
    description: 'Unlocks Cavalry units. Cavalry HP +15%',
    category: 'MILITARY',
    maxLevel: 1,
    costGold: 600,
    costWood: 400,
    costStone: 200,
    costFood: 300,
    researchTimeSeconds: 600,
    prerequisites: ['WEAPON_FORGE_I'],
    mutuallyExclusive: [],
    effects: [{ type: 'UNIT_STAT', target: 'CAVALRY', stat: 'hp', value: 0.15, operation: 'ADD' }],
  },
  {
    id: crypto.randomUUID(),
    techId: 'HEAVY_CAVALRY',
    name: 'Heavy Cavalry',
    description: 'Cavalry defense +20% and attack +10%',
    category: 'MILITARY',
    maxLevel: 1,
    costGold: 1000,
    costWood: 700,
    costStone: 400,
    costFood: 500,
    researchTimeSeconds: 1080,
    prerequisites: ['HORSE_BREEDING'],
    mutuallyExclusive: [],
    effects: [
      { type: 'UNIT_STAT', target: 'CAVALRY', stat: 'defense', value: 0.20, operation: 'ADD' },
      { type: 'UNIT_STAT', target: 'CAVALRY', stat: 'attack', value: 0.10, operation: 'ADD' },
    ],
  },
  {
    id: crypto.randomUUID(),
    techId: 'SIEGE_ENGINEERING',
    name: 'Siege Engineering',
    description: 'Unlocks Siege units. Siege attack +15%',
    category: 'MILITARY',
    maxLevel: 1,
    costGold: 1200,
    costWood: 900,
    costStone: 600,
    costFood: 200,
    researchTimeSeconds: 1200,
    prerequisites: ['WEAPON_FORGE_II'],
    mutuallyExclusive: [],
    effects: [{ type: 'UNIT_STAT', target: 'SIEGE', stat: 'attack', value: 0.15, operation: 'ADD' }],
  },
  {
    id: crypto.randomUUID(),
    techId: 'BALLISTICS',
    name: 'Ballistics',
    description: 'Siege armor penetration +15 and attack +10%',
    category: 'MILITARY',
    maxLevel: 1,
    costGold: 1800,
    costWood: 1200,
    costStone: 800,
    costFood: 300,
    researchTimeSeconds: 1500,
    prerequisites: ['SIEGE_ENGINEERING'],
    mutuallyExclusive: [],
    effects: [
      { type: 'UNIT_STAT', target: 'SIEGE', stat: 'armorPenetration', value: 15, operation: 'ADD' },
      { type: 'UNIT_STAT', target: 'SIEGE', stat: 'attack', value: 0.10, operation: 'ADD' },
    ],
  },
  {
    id: crypto.randomUUID(),
    techId: 'GUERRILLA_TACTICS',
    name: 'Guerrilla Tactics',
    description: 'All unit speed +10%',
    category: 'MILITARY',
    maxLevel: 1,
    costGold: 800,
    costWood: 600,
    costStone: 300,
    costFood: 200,
    researchTimeSeconds: 840,
    prerequisites: ['WEAPON_FORGE_II'],
    mutuallyExclusive: [],
    effects: [{ type: 'UNIT_STAT', target: 'all', stat: 'speed', value: 0.10, operation: 'ADD' }],
  },
  {
    id: crypto.randomUUID(),
    techId: 'MASONRY',
    name: 'Masonry',
    description: 'Tower defense effectiveness +25%',
    category: 'DEFENSE',
    maxLevel: 1,
    costGold: 250,
    costWood: 200,
    costStone: 300,
    costFood: 50,
    researchTimeSeconds: 360,
    prerequisites: [],
    mutuallyExclusive: [],
    effects: [{ type: 'BUILDING_STAT', target: 'TOWER', stat: 'defenseBonus', value: 1.25, operation: 'MULTIPLY' }],
  },
  {
    id: crypto.randomUUID(),
    techId: 'STONE_WALLS',
    name: 'Stone Walls',
    description: 'Tower fortification effectiveness +40%',
    category: 'DEFENSE',
    maxLevel: 1,
    costGold: 600,
    costWood: 400,
    costStone: 600,
    costFood: 100,
    researchTimeSeconds: 720,
    prerequisites: ['MASONRY'],
    mutuallyExclusive: [],
    effects: [{ type: 'BUILDING_STAT', target: 'TOWER', stat: 'defenseBonus', value: 1.40, operation: 'MULTIPLY' }],
  },
  {
    id: crypto.randomUUID(),
    techId: 'WATCHTOWER',
    name: 'Watchtower Network',
    description: 'Tower damage +10 per round',
    category: 'DEFENSE',
    maxLevel: 1,
    costGold: 400,
    costWood: 300,
    costStone: 200,
    costFood: 50,
    researchTimeSeconds: 480,
    prerequisites: ['MASONRY'],
    mutuallyExclusive: [],
    effects: [{ type: 'BUILDING_STAT', target: 'TOWER', stat: 'damage', value: 10, operation: 'ADD' }],
  },
  {
    id: crypto.randomUUID(),
    techId: 'POISONED_ARROWS',
    name: 'Poisoned Arrows',
    description: 'Tower damage +20 per round and Archer attack +10%',
    category: 'DEFENSE',
    maxLevel: 1,
    costGold: 800,
    costWood: 600,
    costStone: 400,
    costFood: 100,
    researchTimeSeconds: 900,
    prerequisites: ['WATCHTOWER', 'REINFORCED_BOWS'],
    mutuallyExclusive: [],
    effects: [
      { type: 'BUILDING_STAT', target: 'TOWER', stat: 'damage', value: 20, operation: 'ADD' },
      { type: 'UNIT_STAT', target: 'ARCHER', stat: 'attack', value: 0.10, operation: 'ADD' },
    ],
  },
  {
    id: crypto.randomUUID(),
    techId: 'FORTIFICATIONS',
    name: 'Fortifications',
    description: 'Tower fortifications +50%',
    category: 'DEFENSE',
    maxLevel: 1,
    costGold: 1500,
    costWood: 1000,
    costStone: 1000,
    costFood: 200,
    researchTimeSeconds: 1500,
    prerequisites: ['STONE_WALLS'],
    mutuallyExclusive: [],
    effects: [{ type: 'BUILDING_STAT', target: 'TOWER', stat: 'defenseBonus', value: 1.50, operation: 'MULTIPLY' }],
  },
  {
    id: crypto.randomUUID(),
    techId: 'SPY_NETWORK',
    name: 'Spy Network',
    description: 'Unlocks Spy units',
    category: 'DEFENSE',
    maxLevel: 1,
    costGold: 500,
    costWood: 300,
    costStone: 100,
    costFood: 100,
    researchTimeSeconds: 600,
    prerequisites: [],
    mutuallyExclusive: [],
    effects: [],
  },
  {
    id: crypto.randomUUID(),
    techId: 'SPEC_SIEGE',
    name: 'Siege Mastery',
    description: 'Siege units: attack +30%, armor penetration +20, HP +20%',
    category: 'MILITARY',
    maxLevel: 1,
    costGold: 2500,
    costWood: 1800,
    costStone: 1200,
    costFood: 500,
    researchTimeSeconds: 2400,
    prerequisites: ['BALLISTICS', 'FORTIFICATIONS'],
    mutuallyExclusive: ['SPEC_CAVALRY'],
    effects: [
      { type: 'UNIT_STAT', target: 'SIEGE', stat: 'attack', value: 0.30, operation: 'ADD' },
      { type: 'UNIT_STAT', target: 'SIEGE', stat: 'armorPenetration', value: 20, operation: 'ADD' },
      { type: 'UNIT_STAT', target: 'SIEGE', stat: 'hp', value: 0.20, operation: 'ADD' },
    ],
  },
  {
    id: crypto.randomUUID(),
    techId: 'SPEC_CAVALRY',
    name: 'Cavalry Mastery',
    description: 'Cavalry units: attack +25%, speed +20%, HP +25%',
    category: 'MILITARY',
    maxLevel: 1,
    costGold: 2500,
    costWood: 1500,
    costStone: 800,
    costFood: 1000,
    researchTimeSeconds: 2400,
    prerequisites: ['HEAVY_CAVALRY', 'STONE_WALLS'],
    mutuallyExclusive: ['SPEC_SIEGE'],
    effects: [
      { type: 'UNIT_STAT', target: 'CAVALRY', stat: 'attack', value: 0.25, operation: 'ADD' },
      { type: 'UNIT_STAT', target: 'CAVALRY', stat: 'speed', value: 0.20, operation: 'ADD' },
      { type: 'UNIT_STAT', target: 'CAVALRY', stat: 'hp', value: 0.25, operation: 'ADD' },
    ],
  },
];
